"""empty message

Revision ID: 6a9e19f02e3e
Revises: 0d9766080de3
Create Date: 2020-06-13 17:58:23.230517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9e19f02e3e'
down_revision = '0d9766080de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmedontario', sa.Column('case_reported_date', sa.DateTime(), nullable=True))
    op.add_column('confirmedontario', sa.Column('specimen_reported_date', sa.DateTime(), nullable=True))
    op.add_column('confirmedontario', sa.Column('test_reported_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_confirmedontario_case_reported_date'), 'confirmedontario', ['case_reported_date'], unique=False)
    op.create_index(op.f('ix_confirmedontario_specimen_reported_date'), 'confirmedontario', ['specimen_reported_date'], unique=False)
    op.create_index(op.f('ix_confirmedontario_test_reported_date'), 'confirmedontario', ['test_reported_date'], unique=False)
    op.add_column('ideamodel', sa.Column('date_retrieved', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_ideamodel_date_retrieved'), 'ideamodel', ['date_retrieved'], unique=False)
    op.add_column('predictivemodel', sa.Column('date_retrieved', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_predictivemodel_date_retrieved'), 'predictivemodel', ['date_retrieved'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictivemodel_date_retrieved'), table_name='predictivemodel')
    op.drop_column('predictivemodel', 'date_retrieved')
    op.drop_index(op.f('ix_ideamodel_date_retrieved'), table_name='ideamodel')
    op.drop_column('ideamodel', 'date_retrieved')
    op.drop_index(op.f('ix_confirmedontario_test_reported_date'), table_name='confirmedontario')
    op.drop_index(op.f('ix_confirmedontario_specimen_reported_date'), table_name='confirmedontario')
    op.drop_index(op.f('ix_confirmedontario_case_reported_date'), table_name='confirmedontario')
    op.drop_column('confirmedontario', 'test_reported_date')
    op.drop_column('confirmedontario', 'specimen_reported_date')
    op.drop_column('confirmedontario', 'case_reported_date')
    # ### end Alembic commands ###
