"""added new things

Revision ID: 1c73f134ebe1
Revises: a3bb76715e08
Create Date: 2020-05-21 16:31:02.398598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c73f134ebe1'
down_revision = 'a3bb76715e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viz', sa.Column('text_bottom', sa.String(), nullable=True))
    op.add_column('viz', sa.Column('text_top', sa.String(), nullable=True))
    op.drop_column('viz', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viz', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('viz', 'text_top')
    op.drop_column('viz', 'text_bottom')
    # ### end Alembic commands ###
