"""added new thing

Revision ID: 24cf166d8f58
Revises: 31b7fc3af7fb
Create Date: 2020-04-10 12:45:33.086360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24cf166d8f58'
down_revision = '31b7fc3af7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viz', sa.Column('desktopHeight', sa.Integer(), nullable=True))
    op.add_column('viz', sa.Column('mobileHeight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viz', 'mobileHeight')
    op.drop_column('viz', 'desktopHeight')
    # ### end Alembic commands ###
