"""added new data sources

Revision ID: 2d5e617e8cef
Revises: e937c0fcdb5c
Create Date: 2020-04-29 11:45:14.916754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d5e617e8cef'
down_revision = 'e937c0fcdb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('longtermcare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('home', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('confirmed_resident_cases', sa.Integer(), nullable=True),
    sa.Column('resident_deaths', sa.Integer(), nullable=True),
    sa.Column('confirmed_staff_cases', sa.Integer(), nullable=True),
    sa.Column('phu', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_longtermcare_date'), 'longtermcare', ['date'], unique=False)
    op.add_column('source', sa.Column('region', sa.String(), nullable=True))
    op.add_column('source', sa.Column('type', sa.String(), nullable=True))
    op.create_index(op.f('ix_source_region'), 'source', ['region'], unique=False)
    op.create_index(op.f('ix_source_type'), 'source', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_type'), table_name='source')
    op.drop_index(op.f('ix_source_region'), table_name='source')
    op.drop_column('source', 'type')
    op.drop_column('source', 'region')
    op.drop_index(op.f('ix_longtermcare_date'), table_name='longtermcare')
    op.drop_table('longtermcare')
    # ### end Alembic commands ###
