"""added new table

Revision ID: 305eeda05ff0
Revises: d4a2ffda87ed
Create Date: 2020-03-30 15:02:29.270441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305eeda05ff0'
down_revision = 'd4a2ffda87ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icucapacity', sa.Column('confirmed_positive_ventilator', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('icucapacity', 'confirmed_positive_ventilator')
    # ### end Alembic commands ###
