"""added new data tables

Revision ID: 31b11ad806a9
Revises: 2d5e617e8cef
Create Date: 2020-05-07 23:03:31.370071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b11ad806a9'
down_revision = '2d5e617e8cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mobilitytransportation', sa.Column('source', sa.String(), nullable=True))
    op.add_column('viz', sa.Column('tab_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viz', 'tab_order')
    op.drop_column('mobilitytransportation', 'source')
    # ### end Alembic commands ###
