"""added new table

Revision ID: 38a564bd1626
Revises: d2509a73ab02
Create Date: 2020-03-30 14:54:31.981162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a564bd1626'
down_revision = 'd2509a73ab02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icucapacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('icu_level', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('lhin', sa.String(), nullable=True),
    sa.Column('critical_care_beds', sa.Integer(), nullable=True),
    sa.Column('critical_care_patients', sa.Integer(), nullable=True),
    sa.Column('vented_beds', sa.Integer(), nullable=True),
    sa.Column('vented_patients', sa.Integer(), nullable=True),
    sa.Column('suspected_covid', sa.Integer(), nullable=True),
    sa.Column('suspected_covid_ventilator', sa.Integer(), nullable=True),
    sa.Column('confirmed_positive', sa.Integer(), nullable=True),
    sa.Column('confirmed_negative', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icucapacity_date'), 'icucapacity', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_icucapacity_date'), table_name='icucapacity')
    op.drop_table('icucapacity')
    # ### end Alembic commands ###
