"""new dbs added

Revision ID: 3a3be47e06c5
Revises: 31b11ad806a9
Create Date: 2020-05-09 13:09:01.516942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3be47e06c5'
down_revision = '31b11ad806a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ideamodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('reported_cases', sa.Integer(), nullable=True),
    sa.Column('model_incident_cases', sa.Float(), nullable=True),
    sa.Column('model_incident_cases_lower_PI', sa.Float(), nullable=True),
    sa.Column('model_incident_cases_upper_PI', sa.Float(), nullable=True),
    sa.Column('reported_cumulative_cases', sa.Integer(), nullable=True),
    sa.Column('model_cumulative_cases', sa.Float(), nullable=True),
    sa.Column('model_cumulative_cases_lower_PI', sa.Float(), nullable=True),
    sa.Column('model_cumulative_cases_upper_PI', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ideamodel_date'), 'ideamodel', ['date'], unique=False)
    op.create_index(op.f('ix_ideamodel_source'), 'ideamodel', ['source'], unique=False)
    op.create_table('predictivemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('cumulative_incidence', sa.Integer(), nullable=True),
    sa.Column('required_hospW', sa.Integer(), nullable=True),
    sa.Column('required_hospNonVentICU', sa.Integer(), nullable=True),
    sa.Column('required_hospVentICU', sa.Integer(), nullable=True),
    sa.Column('available_hospW', sa.Integer(), nullable=True),
    sa.Column('available_hospNonVentICU', sa.Integer(), nullable=True),
    sa.Column('available_hospVentICU', sa.Integer(), nullable=True),
    sa.Column('waiting_hospW', sa.Integer(), nullable=True),
    sa.Column('waiting_hospNonVentICU', sa.Integer(), nullable=True),
    sa.Column('waiting_hospVentICU', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictivemodel_date'), 'predictivemodel', ['date'], unique=False)
    op.create_index(op.f('ix_predictivemodel_region'), 'predictivemodel', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictivemodel_region'), table_name='predictivemodel')
    op.drop_index(op.f('ix_predictivemodel_date'), table_name='predictivemodel')
    op.drop_table('predictivemodel')
    op.drop_index(op.f('ix_ideamodel_source'), table_name='ideamodel')
    op.drop_index(op.f('ix_ideamodel_date'), table_name='ideamodel')
    op.drop_table('ideamodel')
    # ### end Alembic commands ###
