"""created new db

Revision ID: 3eef4dabf053
Revises: 64e46541abc6
Create Date: 2020-06-30 15:20:59.161233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eef4dabf053'
down_revision = '64e46541abc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phuicucapacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('icu_level', sa.String(), nullable=True),
    sa.Column('phu', sa.String(), nullable=True),
    sa.Column('icu_type', sa.String(), nullable=True),
    sa.Column('critical_care_beds', sa.Integer(), nullable=True),
    sa.Column('critical_care_patients', sa.Integer(), nullable=True),
    sa.Column('vented_beds', sa.Integer(), nullable=True),
    sa.Column('vented_patients', sa.Integer(), nullable=True),
    sa.Column('confirmed_positive', sa.Integer(), nullable=True),
    sa.Column('confirmed_positive_ventilator', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phuicucapacity_date'), 'phuicucapacity', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phuicucapacity_date'), table_name='phuicucapacity')
    op.drop_table('phuicucapacity')
    # ### end Alembic commands ###
