"""added PHU capacity

Revision ID: 4408c7b44980
Revises: e46ca5f12457
Create Date: 2020-03-24 09:28:12.921258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4408c7b44980'
down_revision = 'e46ca5f12457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phucapacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('icu', sa.Integer(), nullable=True),
    sa.Column('acute', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phucapacity_name'), 'phucapacity', ['name'], unique=False)
    op.drop_column('comparison', 'hundred')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparison', sa.Column('hundred', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_phucapacity_name'), table_name='phucapacity')
    op.drop_table('phucapacity')
    # ### end Alembic commands ###
