"""linkedin column

Revision ID: 505c88b1d738
Revises: 82760f5aca75
Create Date: 2020-06-14 16:40:03.634935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505c88b1d738'
down_revision = '82760f5aca75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('linkedin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'linkedin')
    # ### end Alembic commands ###
