"""added subscribers

Revision ID: 588a4bb8cee8
Revises: 1ee3422e28c5
Create Date: 2020-11-19 20:29:29.058163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588a4bb8cee8'
down_revision = '1ee3422e28c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=False)
    op.create_index(op.f('ix_subscribers_frequency'), 'subscribers', ['frequency'], unique=False)
    op.create_index(op.f('ix_subscribers_region'), 'subscribers', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_region'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_frequency'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
