"""added internal data

Revision ID: 5cb0647e1289
Revises: fbc4c96fba10
Create Date: 2020-03-27 20:31:53.167411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb0647e1289'
down_revision = 'fbc4c96fba10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_internationaldata_province', table_name='internationaldata')
    op.drop_column('internationaldata', 'province')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internationaldata', sa.Column('province', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_internationaldata_province', 'internationaldata', ['province'], unique=False)
    # ### end Alembic commands ###
