"""adding new tables and merging

Revision ID: 5f38971bea97
Revises: 1c73f134ebe1
Create Date: 2020-05-29 16:14:40.969692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f38971bea97'
down_revision = '1c73f134ebe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmedontario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('accurate_episode_date', sa.DateTime(), nullable=True),
    sa.Column('age_group', sa.String(), nullable=True),
    sa.Column('client_gender', sa.String(), nullable=True),
    sa.Column('case_acquisitionInfo', sa.String(), nullable=True),
    sa.Column('outcome1', sa.String(), nullable=True),
    sa.Column('outbreak_related', sa.String(), nullable=True),
    sa.Column('reporting_phu', sa.String(), nullable=True),
    sa.Column('reporting_phu_address', sa.String(), nullable=True),
    sa.Column('reporting_phu_city', sa.String(), nullable=True),
    sa.Column('reporting_phu_postal_code', sa.String(), nullable=True),
    sa.Column('reporting_phu_website', sa.String(), nullable=True),
    sa.Column('reporting_phu_latitude', sa.String(), nullable=True),
    sa.Column('reporting_phu_longitude', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirmedontario_accurate_episode_date'), 'confirmedontario', ['accurate_episode_date'], unique=False)
    op.create_index(op.f('ix_confirmedontario_row_id'), 'confirmedontario', ['row_id'], unique=False)
    op.create_table('longtermcare_nolongerinoutbreak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('home', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('resident_deaths', sa.Integer(), nullable=True),
    sa.Column('phu', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_longtermcare_nolongerinoutbreak_date'), 'longtermcare_nolongerinoutbreak', ['date'], unique=False)
    op.create_table('longtermcare_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('report', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_longtermcare_summary_date'), 'longtermcare_summary', ['date'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('team_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_first_name'), 'members', ['first_name'], unique=False)
    op.create_index(op.f('ix_members_last_name'), 'members', ['last_name'], unique=False)
    op.create_index(op.f('ix_members_team'), 'members', ['team'], unique=False)
    op.add_column('viz', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('viz', sa.Column('visible', sa.Boolean(), nullable=True))
    op.add_column('viz', sa.Column('viz_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viz', 'viz_title')
    op.drop_column('viz', 'visible')
    op.drop_column('viz', 'date')
    op.drop_index(op.f('ix_members_team'), table_name='members')
    op.drop_index(op.f('ix_members_last_name'), table_name='members')
    op.drop_index(op.f('ix_members_first_name'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_longtermcare_summary_date'), table_name='longtermcare_summary')
    op.drop_table('longtermcare_summary')
    op.drop_index(op.f('ix_longtermcare_nolongerinoutbreak_date'), table_name='longtermcare_nolongerinoutbreak')
    op.drop_table('longtermcare_nolongerinoutbreak')
    op.drop_index(op.f('ix_confirmedontario_row_id'), table_name='confirmedontario')
    op.drop_index(op.f('ix_confirmedontario_accurate_episode_date'), table_name='confirmedontario')
    op.drop_table('confirmedontario')
    # ### end Alembic commands ###
