"""added new table

Revision ID: 6c3fdcfb94c8
Revises: f203d34254ea
Create Date: 2020-04-16 12:10:12.675136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3fdcfb94c8'
down_revision = 'f203d34254ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobilitytransportation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('transportation_type', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobilitytransportation_date'), 'mobilitytransportation', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mobilitytransportation_date'), table_name='mobilitytransportation')
    op.drop_table('mobilitytransportation')
    # ### end Alembic commands ###
