"""added new table

Revision ID: 80f2200c408b
Revises: 24cf166d8f58
Create Date: 2020-04-10 16:39:39.874134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f2200c408b'
down_revision = '24cf166d8f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canadatesting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('cumulative_testing', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canadatesting_date'), 'canadatesting', ['date'], unique=False)
    op.create_index(op.f('ix_canadatesting_province'), 'canadatesting', ['province'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_canadatesting_province'), table_name='canadatesting')
    op.drop_index(op.f('ix_canadatesting_date'), table_name='canadatesting')
    op.drop_table('canadatesting')
    # ### end Alembic commands ###
