"""add hospitalized and icu

Revision ID: 81998c8b1aee
Revises: 10baf88e90a2
Create Date: 2020-04-05 11:46:43.144874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81998c8b1aee'
down_revision = '10baf88e90a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('covidtests', sa.Column('hospitalized', sa.Integer(), nullable=True))
    op.add_column('covidtests', sa.Column('icu', sa.Integer(), nullable=True))
    op.add_column('covidtests', sa.Column('ventilator', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('covidtests', 'ventilator')
    op.drop_column('covidtests', 'icu')
    op.drop_column('covidtests', 'hospitalized')
    # ### end Alembic commands ###
