"""added compiled

Revision ID: d2509a73ab02
Revises: 46a19df7fd8b
Create Date: 2020-03-28 13:42:03.303053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2509a73ab02'
down_revision = '46a19df7fd8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('compiled', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'compiled')
    # ### end Alembic commands ###
