"""removed country

Revision ID: dc927bcd64fa
Revises: 59dc19110661
Create Date: 2020-04-05 13:54:29.799035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc927bcd64fa'
down_revision = '59dc19110661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('canadarecovered', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canadarecovered', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
