"""added new plots

Revision ID: e937c0fcdb5c
Revises: 26c1b7e78e8d
Create Date: 2020-04-27 19:17:29.451707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e937c0fcdb5c'
down_revision = '26c1b7e78e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viz', sa.Column('phu', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viz', 'phu')
    # ### end Alembic commands ###
