"""changed covid to remove source

Revision ID: faaf679b71ce
Revises: d57323c5f17d
Create Date: 2020-03-23 14:18:04.931393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faaf679b71ce'
down_revision = 'd57323c5f17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('covid', 'locala')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('covid', sa.Column('locala', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
