"""empty message

Revision ID: 4b44e86db304
Revises: 
Create Date: 2020-06-11 11:54:24.398346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b44e86db304'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('healthregions')
    op.drop_table('healthregionsdata')
    op.drop_column('ideamodel', 'date_retrieved')
    op.drop_column('predictivemodel', 'date_retrieved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictivemodel', sa.Column('date_retrieved', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('ideamodel', sa.Column('date_retrieved', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('healthregionsdata',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cases_cumulative', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deaths_cumulative', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovered_cumulative', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tests_cumulative', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='healthregionsdata_pkey')
    )
    op.create_table('healthregions',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('province', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('eng_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fr_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='healthregions_pkey')
    )
    # ### end Alembic commands ###
