"""empty message

Revision ID: 24852b55387a
Revises: b4b9356c964a
Create Date: 2020-06-13 17:49:19.367579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24852b55387a'
down_revision = 'b4b9356c964a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmedontario', sa.Column('case_reported_date', sa.DateTime(), nullable=True))
    op.add_column('confirmedontario', sa.Column('specimen_reported_date', sa.DateTime(), nullable=True))
    op.add_column('confirmedontario', sa.Column('test_reported_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_confirmedontario_case_reported_date'), 'confirmedontario', ['case_reported_date'], unique=False)
    op.create_index(op.f('ix_confirmedontario_specimen_reported_date'), 'confirmedontario', ['specimen_reported_date'], unique=False)
    op.create_index(op.f('ix_confirmedontario_test_reported_date'), 'confirmedontario', ['test_reported_date'], unique=False)
    op.create_index(op.f('ix_ideamodel_date_retrieved'), 'ideamodel', ['date_retrieved'], unique=False)
    op.create_index(op.f('ix_predictivemodel_date_retrieved'), 'predictivemodel', ['date_retrieved'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictivemodel_date_retrieved'), table_name='predictivemodel')
    op.drop_index(op.f('ix_ideamodel_date_retrieved'), table_name='ideamodel')
    op.drop_index(op.f('ix_confirmedontario_test_reported_date'), table_name='confirmedontario')
    op.drop_index(op.f('ix_confirmedontario_specimen_reported_date'), table_name='confirmedontario')
    op.drop_index(op.f('ix_confirmedontario_case_reported_date'), table_name='confirmedontario')
    op.drop_column('confirmedontario', 'test_reported_date')
    op.drop_column('confirmedontario', 'specimen_reported_date')
    op.drop_column('confirmedontario', 'case_reported_date')
    # ### end Alembic commands ###
