"""empty message

Revision ID: 2abebc026683
Revises: 796355a21d69
Create Date: 2020-07-08 19:31:05.285442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abebc026683'
down_revision = '796355a21d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phuicucapacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('icu_level', sa.String(), nullable=True),
    sa.Column('phu', sa.String(), nullable=True),
    sa.Column('icu_type', sa.String(), nullable=True),
    sa.Column('critical_care_beds', sa.Integer(), nullable=True),
    sa.Column('critical_care_patients', sa.Integer(), nullable=True),
    sa.Column('vented_beds', sa.Integer(), nullable=True),
    sa.Column('vented_patients', sa.Integer(), nullable=True),
    sa.Column('confirmed_positive', sa.Integer(), nullable=True),
    sa.Column('confirmed_positive_ventilator', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phuicucapacity_date'), 'phuicucapacity', ['date'], unique=False)
    op.create_table('weeklyjobposting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('geography', sa.String(), nullable=True),
    sa.Column('geography_type', sa.String(), nullable=True),
    sa.Column('geography_code', sa.String(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('job_postings_count', sa.String(), nullable=True),
    sa.Column('population', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weeklyjobposting_end_date'), 'weeklyjobposting', ['end_date'], unique=False)
    op.create_index(op.f('ix_weeklyjobposting_start_date'), 'weeklyjobposting', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weeklyjobposting_start_date'), table_name='weeklyjobposting')
    op.drop_index(op.f('ix_weeklyjobposting_end_date'), table_name='weeklyjobposting')
    op.drop_table('weeklyjobposting')
    op.drop_index(op.f('ix_phuicucapacity_date'), table_name='phuicucapacity')
    op.drop_table('phuicucapacity')
    # ### end Alembic commands ###
