"""empty message

Revision ID: 796355a21d69
Revises: 3fedc8df5c4f
Create Date: 2020-06-15 09:52:29.219093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796355a21d69'
down_revision = '3fedc8df5c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('linkedin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'linkedin')
    # ### end Alembic commands ###
