"""empty message

Revision ID: 089dd8fd7372
Revises: f791042e3ceb
Create Date: 2020-07-17 15:27:23.652448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089dd8fd7372'
down_revision = 'f791042e3ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phuicucapacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('icu_level', sa.String(), nullable=True),
    sa.Column('phu', sa.String(), nullable=True),
    sa.Column('icu_type', sa.String(), nullable=True),
    sa.Column('critical_care_beds', sa.Integer(), nullable=True),
    sa.Column('critical_care_patients', sa.Integer(), nullable=True),
    sa.Column('vented_beds', sa.Integer(), nullable=True),
    sa.Column('vented_patients', sa.Integer(), nullable=True),
    sa.Column('confirmed_positive', sa.Integer(), nullable=True),
    sa.Column('confirmed_positive_ventilator', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phuicucapacity_date'), 'phuicucapacity', ['date'], unique=False)
    op.add_column('source', sa.Column('html', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'html')
    op.drop_index(op.f('ix_phuicucapacity_date'), table_name='phuicucapacity')
    op.drop_table('phuicucapacity')
    # ### end Alembic commands ###
