"""empty message

Revision ID: 0d0d42ac0c04
Revises: 5cc26d7323f7
Create Date: 2020-05-15 16:53:10.787191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0d42ac0c04'
down_revision = '5cc26d7323f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viz', sa.Column('viz_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viz', 'viz_type')
    # ### end Alembic commands ###
