"""empty message

Revision ID: 110a27b89211
Revises: 2ae3c47266e4
Create Date: 2020-05-25 00:04:13.714116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110a27b89211'
down_revision = '2ae3c47266e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viz', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viz', 'date')
    # ### end Alembic commands ###
