"""empty message

Revision ID: 2ae3c47266e4
Revises: 85890168227d
Create Date: 2020-05-24 18:39:21.995019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae3c47266e4'
down_revision = '85890168227d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viz', sa.Column('viz_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viz', 'viz_title')
    # ### end Alembic commands ###
