"""empty message

Revision ID: 3bc1376402ad
Revises: 1b9ed2c015a6
Create Date: 2020-06-09 10:23:26.879820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc1376402ad'
down_revision = '1b9ed2c015a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("healthregionsdata")
    op.drop_table("healthregions")
    op.drop_index('ix_healthregions_region_id', table_name='healthregions')
    op.drop_constraint('healthregionsdata_region_id_fkey', 'healthregionsdata', type_='foreignkey')
    op.drop_column('healthregions', 'id')
    op.create_foreign_key(None, 'healthregionsdata', 'healthregions', ['region_id'], ['region_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'healthregionsdata', type_='foreignkey')
    op.create_foreign_key('healthregionsdata_region_id_fkey', 'healthregionsdata', 'healthregions', ['region_id'], ['id'])
    op.add_column('healthregions', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('healthregions_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.create_index('ix_healthregions_region_id', 'healthregions', ['region_id'], unique=False)
    # ### end Alembic commands ###
