"""empty message

Revision ID: 3dc8ca528d73
Revises: ea81b64388c5
Create Date: 2020-04-16 10:51:51.178970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc8ca528d73'
down_revision = 'ea81b64388c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobilitytransportation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('transportation_type', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobilitytransportation_date'), 'mobilitytransportation', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mobilitytransportation_date'), table_name='mobilitytransportation')
    op.drop_table('mobilitytransportation')
    # ### end Alembic commands ###
