"""empty message

Revision ID: 3f8a34da0c1d
Revises: 91a4b71ec6bb
Create Date: 2020-06-15 09:49:38.483798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8a34da0c1d'
down_revision = '91a4b71ec6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('linkedin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'linkedin')
    # ### end Alembic commands ###
