"""empty message

Revision ID: 4b1176c56346
Revises: 22357fc10edc
Create Date: 2020-04-12 18:34:52.679973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1176c56346'
down_revision = '22357fc10edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('contact', sa.String(), nullable=True))
    op.add_column('source', sa.Column('contributor', sa.String(), nullable=True))
    op.add_column('source', sa.Column('data_feed_type', sa.String(), nullable=True))
    op.add_column('source', sa.Column('download', sa.String(), nullable=True))
    op.add_column('source', sa.Column('link', sa.String(), nullable=True))
    op.add_column('source', sa.Column('refresh', sa.String(), nullable=True))
    op.drop_column('source', 'compiled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('compiled', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('source', 'refresh')
    op.drop_column('source', 'link')
    op.drop_column('source', 'download')
    op.drop_column('source', 'data_feed_type')
    op.drop_column('source', 'contributor')
    op.drop_column('source', 'contact')
    # ### end Alembic commands ###
