"""empty message

Revision ID: 585f23a463e5
Revises: 8b23a53009c2
Create Date: 2020-06-12 18:22:53.579605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585f23a463e5'
down_revision = '8b23a53009c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmedontario', sa.Column('case_reported_date', sa.DateTime(), nullable=True))
    op.add_column('confirmedontario', sa.Column('specimen_reported_date', sa.DateTime(), nullable=True))
    op.add_column('confirmedontario', sa.Column('test_reported_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_confirmedontario_case_reported_date'), 'confirmedontario', ['case_reported_date'], unique=False)
    op.create_index(op.f('ix_confirmedontario_specimen_reported_date'), 'confirmedontario', ['specimen_reported_date'], unique=False)
    op.create_index(op.f('ix_confirmedontario_test_reported_date'), 'confirmedontario', ['test_reported_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confirmedontario_test_reported_date'), table_name='confirmedontario')
    op.drop_index(op.f('ix_confirmedontario_specimen_reported_date'), table_name='confirmedontario')
    op.drop_index(op.f('ix_confirmedontario_case_reported_date'), table_name='confirmedontario')
    op.drop_column('confirmedontario', 'test_reported_date')
    op.drop_column('confirmedontario', 'specimen_reported_date')
    op.drop_column('confirmedontario', 'case_reported_date')
    # ### end Alembic commands ###
