"""Added table

Revision ID: 5cc26d7323f7
Revises: 4aa6c3df32f7
Create Date: 2020-05-15 09:15:56.551424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc26d7323f7'
down_revision = '4aa6c3df32f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casesstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reported_date', sa.DateTime(), nullable=True),
    sa.Column('confirmed_negative', sa.Integer(), nullable=True),
    sa.Column('presumptive_negative', sa.Integer(), nullable=True),
    sa.Column('presumptive_positive', sa.Integer(), nullable=True),
    sa.Column('confirmed_positive', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=True),
    sa.Column('patients_approved', sa.Integer(), nullable=True),
    sa.Column('tests_today', sa.Integer(), nullable=True),
    sa.Column('under_investigation', sa.Integer(), nullable=True),
    sa.Column('hospitalized', sa.Integer(), nullable=True),
    sa.Column('icu', sa.Integer(), nullable=True),
    sa.Column('icu_ventilator', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casesstatus_reported_date'), 'casesstatus', ['reported_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_casesstatus_reported_date'), table_name='casesstatus')
    op.drop_table('casesstatus')
    # ### end Alembic commands ###
