"""empty message

Revision ID: 62c0e627b4f6
Revises: 
Create Date: 2020-04-08 10:38:24.146011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c0e627b4f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_date'), 'comparison', ['date'], unique=False)
    op.create_index(op.f('ix_comparison_province'), 'comparison', ['province'], unique=False)
    op.create_table('covid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.String(length=120), nullable=True),
    sa.Column('sex', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('travel', sa.Integer(), nullable=True),
    sa.Column('travelh', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_covid_case_id'), 'covid', ['case_id'], unique=False)
    op.create_index(op.f('ix_covid_date'), 'covid', ['date'], unique=False)
    op.create_table('covidtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('negative', sa.Integer(), nullable=True),
    sa.Column('investigation', sa.Integer(), nullable=True),
    sa.Column('positive', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_covidtests_date'), 'covidtests', ['date'], unique=False)
    op.create_table('internationaldata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('cases', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internationaldata_country'), 'internationaldata', ['country'], unique=False)
    op.create_index(op.f('ix_internationaldata_date'), 'internationaldata', ['date'], unique=False)
    op.create_table('phucapacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('icu', sa.Integer(), nullable=True),
    sa.Column('acute', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phucapacity_name'), 'phucapacity', ['name'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('compiled', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_name'), 'source', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_name'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_phucapacity_name'), table_name='phucapacity')
    op.drop_table('phucapacity')
    op.drop_index(op.f('ix_internationaldata_date'), table_name='internationaldata')
    op.drop_index(op.f('ix_internationaldata_country'), table_name='internationaldata')
    op.drop_table('internationaldata')
    op.drop_index(op.f('ix_covidtests_date'), table_name='covidtests')
    op.drop_table('covidtests')
    op.drop_index(op.f('ix_covid_date'), table_name='covid')
    op.drop_index(op.f('ix_covid_case_id'), table_name='covid')
    op.drop_table('covid')
    op.drop_index(op.f('ix_comparison_province'), table_name='comparison')
    op.drop_index(op.f('ix_comparison_date'), table_name='comparison')
    op.drop_table('comparison')
    # ### end Alembic commands ###
