"""empty message

Revision ID: 6b45458f0c0e
Revises: 282eb30ea314
Create Date: 2021-04-12 21:33:36.156603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b45458f0c0e'
down_revision = '282eb30ea314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmedontario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('accurate_episode_date', sa.DateTime(), nullable=True),
    sa.Column('case_reported_date', sa.DateTime(), nullable=True),
    sa.Column('test_reported_date', sa.DateTime(), nullable=True),
    sa.Column('specimen_reported_date', sa.DateTime(), nullable=True),
    sa.Column('age_group', sa.String(), nullable=True),
    sa.Column('client_gender', sa.String(), nullable=True),
    sa.Column('case_acquisitionInfo', sa.String(), nullable=True),
    sa.Column('outcome1', sa.String(), nullable=True),
    sa.Column('outbreak_related', sa.String(), nullable=True),
    sa.Column('reporting_phu', sa.String(), nullable=True),
    sa.Column('reporting_phu_address', sa.String(), nullable=True),
    sa.Column('reporting_phu_city', sa.String(), nullable=True),
    sa.Column('reporting_phu_postal_code', sa.String(), nullable=True),
    sa.Column('reporting_phu_website', sa.String(), nullable=True),
    sa.Column('reporting_phu_latitude', sa.String(), nullable=True),
    sa.Column('reporting_phu_longitude', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirmedontario_accurate_episode_date'), 'confirmedontario', ['accurate_episode_date'], unique=False)
    op.create_index(op.f('ix_confirmedontario_case_reported_date'), 'confirmedontario', ['case_reported_date'], unique=False)
    op.create_index(op.f('ix_confirmedontario_row_id'), 'confirmedontario', ['row_id'], unique=False)
    op.create_index(op.f('ix_confirmedontario_specimen_reported_date'), 'confirmedontario', ['specimen_reported_date'], unique=False)
    op.create_index(op.f('ix_confirmedontario_test_reported_date'), 'confirmedontario', ['test_reported_date'], unique=False)
    op.create_table('covidtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('negative', sa.Integer(), nullable=True),
    sa.Column('investigation', sa.Integer(), nullable=True),
    sa.Column('positive', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('hospitalized', sa.Integer(), nullable=True),
    sa.Column('icu', sa.Integer(), nullable=True),
    sa.Column('ventilator', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_covidtests_date'), 'covidtests', ['date'], unique=False)
    op.drop_table('alerts')
    op.add_column('subscribers', sa.Column('date_subscribed', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_subscribers_date_subscribed'), 'subscribers', ['date_subscribed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_date_subscribed'), table_name='subscribers')
    op.drop_column('subscribers', 'date_subscribed')
    op.create_table('alerts',
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_covidtests_date'), table_name='covidtests')
    op.drop_table('covidtests')
    op.drop_index(op.f('ix_confirmedontario_test_reported_date'), table_name='confirmedontario')
    op.drop_index(op.f('ix_confirmedontario_specimen_reported_date'), table_name='confirmedontario')
    op.drop_index(op.f('ix_confirmedontario_row_id'), table_name='confirmedontario')
    op.drop_index(op.f('ix_confirmedontario_case_reported_date'), table_name='confirmedontario')
    op.drop_index(op.f('ix_confirmedontario_accurate_episode_date'), table_name='confirmedontario')
    op.drop_table('confirmedontario')
    # ### end Alembic commands ###
