"""empty message

Revision ID: 7080c342a944
Revises: 158e11ad7d91
Create Date: 2020-04-26 19:22:27.094496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7080c342a944'
down_revision = '158e11ad7d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('covid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.String(length=120), nullable=True),
    sa.Column('sex', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('travel', sa.String(), nullable=True),
    sa.Column('travelh', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_covid_case_id'), 'covid', ['case_id'], unique=False)
    op.create_index(op.f('ix_covid_date'), 'covid', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_covid_date'), table_name='covid')
    op.drop_index(op.f('ix_covid_case_id'), table_name='covid')
    op.drop_table('covid')
    # ### end Alembic commands ###
