"""empty message

Revision ID: 70ede0bf65a0
Revises: 224a664bf23c
Create Date: 2020-06-09 10:38:42.390530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ede0bf65a0'
down_revision = '224a664bf23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthregions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('eng_name', sa.String(), nullable=True),
    sa.Column('fr_name', sa.String(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthregions_eng_name'), 'healthregions', ['eng_name'], unique=False)
    op.create_index(op.f('ix_healthregions_fr_name'), 'healthregions', ['fr_name'], unique=False)
    op.create_table('healthregionsdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('cases_cumulative', sa.Integer(), nullable=True),
    sa.Column('deaths_cumulative', sa.Integer(), nullable=True),
    sa.Column('recovered_cumulative', sa.Integer(), nullable=True),
    sa.Column('tests_cumulative', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['healthregions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthregionsdata_date'), 'healthregionsdata', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_healthregionsdata_date'), table_name='healthregionsdata')
    op.drop_table('healthregionsdata')
    op.drop_index(op.f('ix_healthregions_fr_name'), table_name='healthregions')
    op.drop_index(op.f('ix_healthregions_eng_name'), table_name='healthregions')
    op.drop_table('healthregions')
    # ### end Alembic commands ###
