"""empty message

Revision ID: 85890168227d
Revises: dddf864da253
Create Date: 2020-05-23 10:55:45.677118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85890168227d'
down_revision = 'dddf864da253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmedontario', sa.Column('accurate_episode_date', sa.DateTime(), nullable=True))
    op.add_column('confirmedontario', sa.Column('age_group', sa.String(), nullable=True))
    op.add_column('confirmedontario', sa.Column('case_acquisitionInfo', sa.String(), nullable=True))
    op.add_column('confirmedontario', sa.Column('client_gender', sa.String(), nullable=True))
    op.add_column('confirmedontario', sa.Column('outbreak_related', sa.String(), nullable=True))
    op.add_column('confirmedontario', sa.Column('outcome1', sa.String(), nullable=True))
    op.add_column('confirmedontario', sa.Column('reporting_phu', sa.String(), nullable=True))
    op.add_column('confirmedontario', sa.Column('reporting_phu_address', sa.String(), nullable=True))
    op.add_column('confirmedontario', sa.Column('reporting_phu_city', sa.String(), nullable=True))
    op.add_column('confirmedontario', sa.Column('reporting_phu_latitude', sa.String(), nullable=True))
    op.add_column('confirmedontario', sa.Column('reporting_phu_longitude', sa.String(), nullable=True))
    op.add_column('confirmedontario', sa.Column('reporting_phu_postal_code', sa.String(), nullable=True))
    op.add_column('confirmedontario', sa.Column('reporting_phu_website', sa.String(), nullable=True))
    op.create_index(op.f('ix_confirmedontario_accurate_episode_date'), 'confirmedontario', ['accurate_episode_date'], unique=False)
    op.drop_index('ix_confirmedontario_Accurate_Episode_Date', table_name='confirmedontario')
    op.drop_column('confirmedontario', 'Case_AcquisitionInfo')
    op.drop_column('confirmedontario', 'Outcome1')
    op.drop_column('confirmedontario', 'Reporting_PHU_Address')
    op.drop_column('confirmedontario', 'Reporting_PHU')
    op.drop_column('confirmedontario', 'Outbreak_Related')
    op.drop_column('confirmedontario', 'Reporting_PHU_Website')
    op.drop_column('confirmedontario', 'Reporting_PHU_Longitude')
    op.drop_column('confirmedontario', 'Reporting_PHU_City')
    op.drop_column('confirmedontario', 'Reporting_PHU_Latitude')
    op.drop_column('confirmedontario', 'Client_Gender')
    op.drop_column('confirmedontario', 'Age_Group')
    op.drop_column('confirmedontario', 'Reporting_PHU_Postal_Code')
    op.drop_column('confirmedontario', 'Accurate_Episode_Date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmedontario', sa.Column('Accurate_Episode_Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('confirmedontario', sa.Column('Reporting_PHU_Postal_Code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('confirmedontario', sa.Column('Age_Group', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('confirmedontario', sa.Column('Client_Gender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('confirmedontario', sa.Column('Reporting_PHU_Latitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('confirmedontario', sa.Column('Reporting_PHU_City', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('confirmedontario', sa.Column('Reporting_PHU_Longitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('confirmedontario', sa.Column('Reporting_PHU_Website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('confirmedontario', sa.Column('Outbreak_Related', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('confirmedontario', sa.Column('Reporting_PHU', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('confirmedontario', sa.Column('Reporting_PHU_Address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('confirmedontario', sa.Column('Outcome1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('confirmedontario', sa.Column('Case_AcquisitionInfo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_confirmedontario_Accurate_Episode_Date', 'confirmedontario', ['Accurate_Episode_Date'], unique=False)
    op.drop_index(op.f('ix_confirmedontario_accurate_episode_date'), table_name='confirmedontario')
    op.drop_column('confirmedontario', 'reporting_phu_website')
    op.drop_column('confirmedontario', 'reporting_phu_postal_code')
    op.drop_column('confirmedontario', 'reporting_phu_longitude')
    op.drop_column('confirmedontario', 'reporting_phu_latitude')
    op.drop_column('confirmedontario', 'reporting_phu_city')
    op.drop_column('confirmedontario', 'reporting_phu_address')
    op.drop_column('confirmedontario', 'reporting_phu')
    op.drop_column('confirmedontario', 'outcome1')
    op.drop_column('confirmedontario', 'outbreak_related')
    op.drop_column('confirmedontario', 'client_gender')
    op.drop_column('confirmedontario', 'case_acquisitionInfo')
    op.drop_column('confirmedontario', 'age_group')
    op.drop_column('confirmedontario', 'accurate_episode_date')
    # ### end Alembic commands ###
