"""empty message

Revision ID: 8b23a53009c2
Revises: 45c50a37fca9
Create Date: 2020-06-12 18:21:09.293687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b23a53009c2'
down_revision = '45c50a37fca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_healthregions_eng_name', table_name='healthregions')
    op.drop_index('ix_healthregions_fr_name', table_name='healthregions')
    op.drop_table('healthregions')
    op.drop_index('ix_healthregionsdata_date', table_name='healthregionsdata')
    op.drop_table('healthregionsdata')
    op.add_column('confirmedontario', sa.Column('case_reported_date', sa.DateTime(), nullable=True))
    op.add_column('confirmedontario', sa.Column('specimen_reported_date', sa.DateTime(), nullable=True))
    op.add_column('confirmedontario', sa.Column('test_reported_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_confirmedontario_case_reported_date'), 'confirmedontario', ['case_reported_date'], unique=False)
    op.create_index(op.f('ix_confirmedontario_specimen_reported_date'), 'confirmedontario', ['specimen_reported_date'], unique=False)
    op.create_index(op.f('ix_confirmedontario_test_reported_date'), 'confirmedontario', ['test_reported_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confirmedontario_test_reported_date'), table_name='confirmedontario')
    op.drop_index(op.f('ix_confirmedontario_specimen_reported_date'), table_name='confirmedontario')
    op.drop_index(op.f('ix_confirmedontario_case_reported_date'), table_name='confirmedontario')
    op.drop_column('confirmedontario', 'test_reported_date')
    op.drop_column('confirmedontario', 'specimen_reported_date')
    op.drop_column('confirmedontario', 'case_reported_date')
    op.create_table('healthregionsdata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cases_cumulative', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deaths_cumulative', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovered_cumulative', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tests_cumulative', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['healthregions.id'], name='healthregionsdata_region_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='healthregionsdata_pkey')
    )
    op.create_index('ix_healthregionsdata_date', 'healthregionsdata', ['date'], unique=False)
    op.create_table('healthregions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('province', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('eng_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fr_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='healthregions_pkey')
    )
    op.create_index('ix_healthregions_fr_name', 'healthregions', ['fr_name'], unique=False)
    op.create_index('ix_healthregions_eng_name', 'healthregions', ['eng_name'], unique=False)
    # ### end Alembic commands ###
