"""empty message

Revision ID: 8ff163281894
Revises: 2af790d8c5e1
Create Date: 2020-04-10 12:21:08.816607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff163281894'
down_revision = '2af790d8c5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viz', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viz', 'height')
    # ### end Alembic commands ###
