"""added new table

Revision ID: 958c4842efef
Revises: 7080c342a944
Create Date: 2020-04-28 12:20:38.153106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958c4842efef'
down_revision = '7080c342a944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('longtermcare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('home', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('confirmed_resident_cases', sa.Integer(), nullable=True),
    sa.Column('resident_deaths', sa.Integer(), nullable=True),
    sa.Column('confirmed_staff_cases', sa.Integer(), nullable=True),
    sa.Column('phu', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_longtermcare_date'), 'longtermcare', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_longtermcare_date'), table_name='longtermcare')
    op.drop_table('longtermcare')
    # ### end Alembic commands ###
