"""empty message

Revision ID: a7535fc05877
Revises: 31d419236710
Create Date: 2020-05-28 22:57:43.069702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7535fc05877'
down_revision = '31d419236710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viz', sa.Column('visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viz', 'visible')
    # ### end Alembic commands ###
