"""empty message

Revision ID: d35cfdf225a0
Revises: d1fac7de50f4
Create Date: 2020-06-15 09:09:12.064199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35cfdf225a0'
down_revision = 'd1fac7de50f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npiinterventions_world', sa.Column('stringency_index_for_display', sa.String(), nullable=True))
    op.drop_column('npiinterventions_world', 'stringencyIndexForDisplay')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npiinterventions_world', sa.Column('stringencyIndexForDisplay', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('npiinterventions_world', 'stringency_index_for_display')
    # ### end Alembic commands ###
