"""empty message

Revision ID: d44c527f9bb6
Revises: 955827537382
Create Date: 2020-04-08 11:37:57.194481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44c527f9bb6'
down_revision = '955827537382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viz', 'route')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viz', sa.Column('route', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
