"""empty message

Revision ID: d80417a5df35
Revises: 62c0e627b4f6
Create Date: 2020-04-08 10:43:01.575555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80417a5df35'
down_revision = '62c0e627b4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canadamortality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('death_id', sa.Integer(), nullable=True),
    sa.Column('province_death_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('death_source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canadamortality_date'), 'canadamortality', ['date'], unique=False)
    op.create_index(op.f('ix_canadamortality_death_id'), 'canadamortality', ['death_id'], unique=False)
    op.create_index(op.f('ix_canadamortality_province_death_id'), 'canadamortality', ['province_death_id'], unique=False)
    op.create_table('canadarecovered',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('cumulative_recovered', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canadarecovered_date'), 'canadarecovered', ['date'], unique=False)
    op.create_index(op.f('ix_canadarecovered_province'), 'canadarecovered', ['province'], unique=False)
    op.create_table('icucapacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('icu_level', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('lhin', sa.String(), nullable=True),
    sa.Column('critical_care_beds', sa.Integer(), nullable=True),
    sa.Column('critical_care_patients', sa.Integer(), nullable=True),
    sa.Column('vented_beds', sa.Integer(), nullable=True),
    sa.Column('vented_patients', sa.Integer(), nullable=True),
    sa.Column('suspected_covid', sa.Integer(), nullable=True),
    sa.Column('suspected_covid_ventilator', sa.Integer(), nullable=True),
    sa.Column('confirmed_positive', sa.Integer(), nullable=True),
    sa.Column('confirmed_positive_ventilator', sa.Integer(), nullable=True),
    sa.Column('confirmed_negative', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icucapacity_date'), 'icucapacity', ['date'], unique=False)
    op.create_table('internationalmortality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internationalmortality_country'), 'internationalmortality', ['country'], unique=False)
    op.create_index(op.f('ix_internationalmortality_date'), 'internationalmortality', ['date'], unique=False)
    op.create_table('internationalrecovered',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('recovered', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internationalrecovered_country'), 'internationalrecovered', ['country'], unique=False)
    op.create_index(op.f('ix_internationalrecovered_date'), 'internationalrecovered', ['date'], unique=False)
    op.create_table('npiinterventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('intervention_summary', sa.String(), nullable=True),
    sa.Column('intervention_category', sa.String(), nullable=True),
    sa.Column('target_population_category', sa.String(), nullable=True),
    sa.Column('enforcement_category', sa.String(), nullable=True),
    sa.Column('oxford_government_response_category', sa.String(), nullable=True),
    sa.Column('oxford_closure_code', sa.String(), nullable=True),
    sa.Column('oxford_public_info_code', sa.String(), nullable=True),
    sa.Column('oxford_travel_code', sa.String(), nullable=True),
    sa.Column('oxford_geographic_target_code', sa.String(), nullable=True),
    sa.Column('oxford_fiscal_measure_cad', sa.String(), nullable=True),
    sa.Column('oxford_monetary_measure', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_organization', sa.String(), nullable=True),
    sa.Column('source_organization_two', sa.String(), nullable=True),
    sa.Column('source_category', sa.String(), nullable=True),
    sa.Column('source_title', sa.String(), nullable=True),
    sa.Column('source_full_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npiinterventions_country'), 'npiinterventions', ['country'], unique=False)
    op.create_index(op.f('ix_npiinterventions_end_date'), 'npiinterventions', ['end_date'], unique=False)
    op.create_index(op.f('ix_npiinterventions_intervention_summary'), 'npiinterventions', ['intervention_summary'], unique=False)
    op.create_index(op.f('ix_npiinterventions_region'), 'npiinterventions', ['region'], unique=False)
    op.create_index(op.f('ix_npiinterventions_start_date'), 'npiinterventions', ['start_date'], unique=False)
    op.add_column('covidtests', sa.Column('hospitalized', sa.Integer(), nullable=True))
    op.add_column('covidtests', sa.Column('icu', sa.Integer(), nullable=True))
    op.add_column('covidtests', sa.Column('ventilator', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('covidtests', 'ventilator')
    op.drop_column('covidtests', 'icu')
    op.drop_column('covidtests', 'hospitalized')
    op.drop_index(op.f('ix_npiinterventions_start_date'), table_name='npiinterventions')
    op.drop_index(op.f('ix_npiinterventions_region'), table_name='npiinterventions')
    op.drop_index(op.f('ix_npiinterventions_intervention_summary'), table_name='npiinterventions')
    op.drop_index(op.f('ix_npiinterventions_end_date'), table_name='npiinterventions')
    op.drop_index(op.f('ix_npiinterventions_country'), table_name='npiinterventions')
    op.drop_table('npiinterventions')
    op.drop_index(op.f('ix_internationalrecovered_date'), table_name='internationalrecovered')
    op.drop_index(op.f('ix_internationalrecovered_country'), table_name='internationalrecovered')
    op.drop_table('internationalrecovered')
    op.drop_index(op.f('ix_internationalmortality_date'), table_name='internationalmortality')
    op.drop_index(op.f('ix_internationalmortality_country'), table_name='internationalmortality')
    op.drop_table('internationalmortality')
    op.drop_index(op.f('ix_icucapacity_date'), table_name='icucapacity')
    op.drop_table('icucapacity')
    op.drop_index(op.f('ix_canadarecovered_province'), table_name='canadarecovered')
    op.drop_index(op.f('ix_canadarecovered_date'), table_name='canadarecovered')
    op.drop_table('canadarecovered')
    op.drop_index(op.f('ix_canadamortality_province_death_id'), table_name='canadamortality')
    op.drop_index(op.f('ix_canadamortality_death_id'), table_name='canadamortality')
    op.drop_index(op.f('ix_canadamortality_date'), table_name='canadamortality')
    op.drop_table('canadamortality')
    # ### end Alembic commands ###
