"""empty message

Revision ID: d9ff7ded32dd
Revises: 089dd8fd7372
Create Date: 2020-07-22 14:29:47.997510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ff7ded32dd'
down_revision = '089dd8fd7372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_update_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('date_refreshed', sa.DateTime(), nullable=True),
    sa.Column('recent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_update_date_date_refreshed'), 'metric_update_date', ['date_refreshed'], unique=False)
    op.create_index(op.f('ix_metric_update_date_source'), 'metric_update_date', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_update_date_source'), table_name='metric_update_date')
    op.drop_index(op.f('ix_metric_update_date_date_refreshed'), table_name='metric_update_date')
    op.drop_table('metric_update_date')
    # ### end Alembic commands ###
