"""empty message

Revision ID: dddf864da253
Revises: 53e5dd8445f9
Create Date: 2020-05-23 10:50:58.150802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dddf864da253'
down_revision = '53e5dd8445f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmedontario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('Accurate_Episode_Date', sa.DateTime(), nullable=True),
    sa.Column('Age_Group', sa.String(), nullable=True),
    sa.Column('Client_Gender', sa.String(), nullable=True),
    sa.Column('Case_AcquisitionInfo', sa.String(), nullable=True),
    sa.Column('Outcome1', sa.String(), nullable=True),
    sa.Column('Outbreak_Related', sa.String(), nullable=True),
    sa.Column('Reporting_PHU', sa.String(), nullable=True),
    sa.Column('Reporting_PHU_Address', sa.String(), nullable=True),
    sa.Column('Reporting_PHU_City', sa.String(), nullable=True),
    sa.Column('Reporting_PHU_Postal_Code', sa.String(), nullable=True),
    sa.Column('Reporting_PHU_Website', sa.String(), nullable=True),
    sa.Column('Reporting_PHU_Latitude', sa.String(), nullable=True),
    sa.Column('Reporting_PHU_Longitude', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirmedontario_Accurate_Episode_Date'), 'confirmedontario', ['Accurate_Episode_Date'], unique=False)
    op.create_index(op.f('ix_confirmedontario_row_id'), 'confirmedontario', ['row_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confirmedontario_row_id'), table_name='confirmedontario')
    op.drop_index(op.f('ix_confirmedontario_Accurate_Episode_Date'), table_name='confirmedontario')
    op.drop_table('confirmedontario')
    # ### end Alembic commands ###
