"""empty message

Revision ID: fa524abadfce
Revises: 7d9ad2b97832
Create Date: 2020-05-04 12:25:33.353615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa524abadfce'
down_revision = '7d9ad2b97832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viz', sa.Column('tab_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viz', 'tab_order')
    # ### end Alembic commands ###
