"""new tables

Revision ID: fefd0f08a1e6
Revises: a7535fc05877
Create Date: 2020-06-08 15:39:36.578730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefd0f08a1e6'
down_revision = 'a7535fc05877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ideamodel_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_retrieved', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('reported_cases', sa.Integer(), nullable=True),
    sa.Column('model_incident_cases', sa.Float(), nullable=True),
    sa.Column('model_incident_cases_lower_PI', sa.Float(), nullable=True),
    sa.Column('model_incident_cases_upper_PI', sa.Float(), nullable=True),
    sa.Column('reported_cumulative_cases', sa.Integer(), nullable=True),
    sa.Column('model_cumulative_cases', sa.Float(), nullable=True),
    sa.Column('model_cumulative_cases_lower_PI', sa.Float(), nullable=True),
    sa.Column('model_cumulative_cases_upper_PI', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ideamodel_timeline_date'), 'ideamodel_timeline', ['date'], unique=False)
    op.create_index(op.f('ix_ideamodel_timeline_date_retrieved'), 'ideamodel_timeline', ['date_retrieved'], unique=False)
    op.create_index(op.f('ix_ideamodel_timeline_source'), 'ideamodel_timeline', ['source'], unique=False)
    op.create_table('predictivemodel_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_retrieved', sa.DateTime(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('cumulative_incidence', sa.Integer(), nullable=True),
    sa.Column('required_hospW', sa.Integer(), nullable=True),
    sa.Column('required_hospNonVentICU', sa.Integer(), nullable=True),
    sa.Column('required_hospVentICU', sa.Integer(), nullable=True),
    sa.Column('available_hospW', sa.Integer(), nullable=True),
    sa.Column('available_hospNonVentICU', sa.Integer(), nullable=True),
    sa.Column('available_hospVentICU', sa.Integer(), nullable=True),
    sa.Column('waiting_hospW', sa.Integer(), nullable=True),
    sa.Column('waiting_hospNonVentICU', sa.Integer(), nullable=True),
    sa.Column('waiting_hospVentICU', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictivemodel_timeline_date'), 'predictivemodel_timeline', ['date'], unique=False)
    op.create_index(op.f('ix_predictivemodel_timeline_date_retrieved'), 'predictivemodel_timeline', ['date_retrieved'], unique=False)
    op.create_index(op.f('ix_predictivemodel_timeline_region'), 'predictivemodel_timeline', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictivemodel_timeline_region'), table_name='predictivemodel_timeline')
    op.drop_index(op.f('ix_predictivemodel_timeline_date_retrieved'), table_name='predictivemodel_timeline')
    op.drop_index(op.f('ix_predictivemodel_timeline_date'), table_name='predictivemodel_timeline')
    op.drop_table('predictivemodel_timeline')
    op.drop_index(op.f('ix_ideamodel_timeline_source'), table_name='ideamodel_timeline')
    op.drop_index(op.f('ix_ideamodel_timeline_date_retrieved'), table_name='ideamodel_timeline')
    op.drop_index(op.f('ix_ideamodel_timeline_date'), table_name='ideamodel_timeline')
    op.drop_table('ideamodel_timeline')
    # ### end Alembic commands ###
